spring:
  profiles:
    active: local
    group:
      local: local_server, common,secret
      blue: blue_server , common, secret
      green: green_server , common, secret
  mvc:
    path match:
      matching-strategy: ant_path_matcher

---

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha


---

spring:
  config:
    activate:
      on-profile: local_server
server:
  port: 8080
client:
  address: http://localhost:3000

---

spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
client:
  address: https://d3g9ccba5dsm6w.cloudfront.net/

---

spring:
  config:
    activate:
      on-profile: green_server
server:
  port: 9090
client:
  address: https://d3g9ccba5dsm6w.cloudfront.net/

---

spring:
  config:
    activate:
      on-profile: common
mybatis:
  mapper-location: mappers/*.xml
  local: local, common, secret
  blue: blue, common, secret
  green: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
          naver:
            redirectUri: http://localhost:8080/login/oauth2/code/naver

server:
  port: 8080
  address: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirectUri: http://13.209.243.191/login/oauth2/code/kakao
          naver:
            redirectUri: http://13.209.243.191/login/oauth2/code/naver

server:
  port: 8080
  address: 13.209.243.191

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirectUri: http://13.209.243.191/login/oauth2/code/kakao
          naver:
            redirectUri: http://13.209.243.191/login/oauth2/code/naver

server:
  port: 8081
  address: 13.209.243.191

serverName: green_server

---

spring:
  config:
    import: application-secret.yml
  mvc:
    path match:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations:
    - /mappers/*.xml

---

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
