version: "3.2"

services:
  finalProject:
    image: mysql:latest  # MySQL 이미지 사용
    container_name: mysql-finalProject
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "3308:3306"  # 호스트 3308 포트 -> 컨테이너 3306 포트로 연결
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finalProject  # 데이터베이스 이름 설정
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ 기본 AMQP 포트
      - "15672:15672" # RabbitMQ 관리 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network

  app:
    build: .   # 현재 디렉토리의 Dockerfile을 사용하여 빌드
    container_name: springboot-app
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - my_network

networks:
  my_network: