### UserSignup
POST {{domain}}/user/signup
Content-Type: application/json

{
  "username" :"test112352",
  "password" : "!Test1234",
  "checkPassword" : "!Test1234",
  "name" : "길동",
  "email" : "test@naver.com",
  "phoneNumber": "010-9548-2134",
  "nickname" : "기동이",
  "role" : "USER"
}

### UserSignin
POST {{domain}}/user/signin
Content-Type: application/json

{
  "username" : "test1123",
  "password" : "!Test1234",
  "role" : "USER"
}

### user/me
GET {{domain}}/user/me

### user프로필 중복
GET {{domain}}/user/duplicated/username?value=test1234